### ISSUE TITLE
npm run rpc 出现Error: spawn mvn ENOENT

### ISSUE THREAD

**Issue by GeniusBrother** [eggjs/egg-sofa-rpc#13]
使用 https://github.com/eggjs/examples/tree/master/sofa-rpc  下的demo项目 

npm i 安装依赖后 执行npm run rpc 出现如下错误
![image](https://user-images.githubusercontent.com/13958352/97107426-69f57700-1702-11eb-8d9b-80b8396970ee.png)

不过rpc服务能正常提供。

**Comment by atian25** [comment]
maven 没安装吧，按文档走

**Comment by GeniusBrother** [comment]
> maven 没安装吧，按文档走

感谢大佬，已经解决，我是看这个文档，上面没标注要安装maven, 不懂Java 所以部署需mvn这个命令，另外 这个文档中在config.{env}.js文件配置rpc插件的配置时写成sofaRpc, 看样子应该是rpc

**Comment by atian25** [comment]
可以提 PR 优化下，之前好像有过一个变更
