### ISSUE TITLE
按照官方给的教程proxy生成不了

### ISSUE THREAD

**Issue by monkeyWie** [eggjs/egg-sofa-rpc#8]
```
npm run rpc
```
错误日志如下：
PluginSequencifyError: sequencify plugins has problem, missing: [rpc], recursive: []
        >> Plugin [rpc] is disabled or missed, but is required by [sofaRpc]

**Comment by xiangnuans** [comment]
你好！这个问题解决了吗？

**Comment by monkeyWie** [comment]
@CoCoyh 没有。。 自己开发了一套typescript版的sdk生成工具

**Comment by wwl88436384** [comment]
`rpc:{
    enable: true,
    package: 'sofa-rpc-node',
  }`
在config/plugin.js里添加这个就可以生成了
但是ctx.proxy 是undefined

**Comment by wwl88436384** [comment]
> `rpc:{ enable: true, package: 'sofa-rpc-node', }`
> 在config/plugin.js里添加这个就可以生成了
> 但是ctx.proxy 是undefined

https://github.com/eggjs/egg-rpc-generator/issues/6 参考这个就可以解决所有问题
